# name: point
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION
      - AWS_BUCKET
      - POSTGRES_CONN
    ports:
      - "5000:80"
    networks:
      - network

networks:
  network:
    driver: bridge

