services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: point-frontend:${BUILD_VERSION}
    restart: unless-stopped
    ports:
      - "127.0.0.1:81:80" 
    networks:
      - point-network
    security_opt:
      - no-new-privileges:true  # deny for new priviligiftion
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # new
    read_only: true  # only reed files to container
    tmpfs:  # directory for write
      - /var/cache/nginx:rw,exec,nosuid,size=100M
      - /var/cache/nginx/client_temp:rw,exec,nosuid,size=50M
      - /var/cache/nginx/proxy_temp:rw,exec,nosuid,size=50M
      - /var/cache/nginx/fastcgi_temp:rw,exec,nosuid,size=50M
      - /var/cache/nginx/uwsgi_temp:rw,exec,nosuid,size=50M
      - /var/cache/nginx/scgi_temp:rw,exec,nosuid,size=50M
      - /var/log/nginx:rw,exec,nosuid,size=100M
      - /run:rw,exec,nosuid,size=50M
      - /tmp:rw,exec,nosuid,size=50M
    # new
networks:
  point-network:
    external: true
    name: point-network
