---
- name: COPY FILES
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('jenkins') }}"
    group: "{{ item.group | default('jenkins') }}"
    force: "{{ item.force | default('true') }}"
  with_items:
    - { src: 'files//Dockerfile', dest: "{{ backend_path }}" }
    - { src: 'files/docker-compose.yml', dest: "{{ backend_path }}" }

- name: CREATE CONFIG IS JINJA
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    validate: jq . %s
  loop:
    - { src: 'azuresettings.json.j2', dest: "{{ backend_path }}/azuresettings.json" }
    - { src: 'awss3settings.json.j2', dest: "{{ backend_path }}/awss3settings.json" }
    - { src: 'postgressettings.json.j2', dest: "{{ backend_path }}/postgressettings.json" }
  no_log: true


