---
- name: Create Docker network
  community.docker.docker_network:
    name: point-network
    driver: bridge
    state: present

- name: START COMPOSE FILE
  community.docker.docker_compose_v2:
    build: always
    check_files_existing: true
    # project_name: point
    project_src: "{{ backend_path }}"
    state: present
    pull: missing
    # remove_orphans: yes
    remove_images: local
  environment:    
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
    AWS_BUCKET: "{{ aws_bucket }}"
    POSTGRES_CONN: "{{ postgres_conn }}"
    BUILD_VERSION: "{{ build_version }}"
    # NEW ENVIROMENT
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_PORT: "{{ DB_PORT }}"
    DB_NAME: "{{ DB_NAME }}"
    DB_USER: "{{ DB_USER }}"

